@echo off
cd /d "%~dp0"
echo Generating catalog from CSVs...
python cataloger.py --csv-folder data --out catalog.json
echo Enriching catalog and creating reports...
python enrich_and_report.py --catalog catalog.json
echo Generating pretty HTML report...
python create_pretty_report.py
echo Launching Streamlit UI (if available)...
python -m streamlit run streamlit_app.py -- --catalog catalog.json
